# Chekov application configuration
defaults: &defaults
  enumables:
    constantize?: true
    classes: [ 'Status', 'Role', 'Permission', 'Team' ]
  view:
    custom_filters: [ 'mine', 'unassigned', 'active' ]
  datetime:
    # Jul 4, 2013 2:09 PM
    med: "%b %e, %Y  %l:%M %p"
  events:
    models_audited: [ 'task', 'comment', 'user' ]
    prefixes: [ 'creat', 'updat', 'delet' ]
  activity_feed:
    top_commenters:
        max: 5
    top_reporters:
        max: 5
    top_activities:
        max: 7

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults