source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Redis and Reseque for handling event notifications for queue
gem 'redis'
gem 'resque'

# small gem handles YAML <-> Settings object for app config files
gem 'settingslogic'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

group :development do
  gem 'haml-rails'
  gem 'rspec-rails'
end

group :test do
	# Testing-related gems
	gem 'capybara'
	gem 'cucumber-rails', require: false
	gem 'factory_girl'
	gem 'factory_girl_rails'
	gem 'database_cleaner'
	gem 'shoulda'
	gem 'rspec-rails'
	gem 'autotest'
	gem 'guard-rspec'
	gem 'guard-cucumber'
	gem 'guard-livereload'
	gem 'rb-fsevent' # Guard needs this
	gem 'growl' # optional - if you like notifications on Mac
end

# Debugging
gem 'pry'
gem 'rails-pry'
gem 'better_errors'
# gem 'binding_of_caller'

# templates
gem 'haml'

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
